# adapted from
# https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
name: pytest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        poetry-options: ["", "--extras=pandas", "&& poetry add pandas=^1.5.3"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.6.1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install --no-interaction --no-root ${{ matrix.poetry-options }}
      - run: poetry run pytest
